// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxjkvaxukdexxwbaaqej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4amt2YXh1a2RleHh3YmFhcWVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NDg3NjQsImV4cCI6MjA3NDEyNDc2NH0.AQTJGSWR5wx3xXMCBIiRICBGG4y4VWeVqkKS9hFgcRw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});